keys:
  - &hosts:
    - &exaflare age1lzurp5dvgpgeqhan7sf5aftc6wphf0kkvjyyznpf6s7uwpvlf5lszracjc
    - &annihilation age1242kck29d7z36a5qewzxeyn3crrujp306qd0nwv7fnx4aadnq5rs339nfv

creation_rules:
  - path_regex: hosts/secrets.ya?ml
    key_groups:
      - age:
        - *exaflare

  - path_regex: hosts/secrets.ya?ml
    key_groups:
      - age:
        - *annihilation

  - path_regex: hosts/secrets.ya?ml
    key_groups:
      - age:
        - *exaflare
        - *annihilation
