{
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (config.colorscheme) colors harmonized;
  customCSS =
    # scss
    ''
      /**
      * @name Luke's Nocturnal Variant
      * @version 1.0.0
      * @description Stylized, Autogenerated, clean. Nocturnal theme with custom font and badges.
      * @author Roottwo
      */

      @import url("https://slowstab.github.io/dracula/BetterDiscord/source.css");
      @import url("https://mulverinex.github.io/legacy-settings-icons/dist-native.css");
      @import url("https://xcruxiex.github.io/themes/themes-cores/nocturnal.css");
      @import url("https://xcruxiex.github.io/themes/core/badges.css");
      @import url("https://xcruxiex.github.io/themes/core/custom-font.css");
      @import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css"); /* Radial Status */
      :root {
        --backgroundColor01: ${colors.surface};
        --backgroundColor02: ${colors.surface_dim};
        --mainColor: ${colors.primary};
        --gradientColor01: ${colors.primary};
        --gradientColor02: ${colors.tertiary};

        /* Better Hljs */
        --backgroundCode: ${colors.surface};
        --backgroundName: ${colors.surface}40;

        /* Radial Status */
        --rs-small-spacing: 2px;
        --rs-large-spacing: 3px;
        --rs-width: 2px;
        --rs-avatar-shape: 70%;
        --rs-online-color: ${harmonized.green};
        --rs-idle-color: ${harmonized.yellow};
        --rs-dnd-color: ${harmonized.red};
        --rs-offline-color: ${harmonized.blue};
        --rs-streaming-color: ${harmonized.magenta};
        --rs-invisible-color: ${harmonized.cyan};
        --rs-phone-visible: block;
        --rs-phone-color: var(--rs-online-color);
        --customFont: 'gg sans', sans-serif;
      }

      .theme-dark, .theme-light, :root {
        --text-default: ${colors.on_surface};
        --header-primary: ${colors.on_surface};
        --header-secondary: ${colors.on_surface_variant};
        --channeltextarea-background: ${colors.surface_container};
        --interactive-normal: ${colors.surface_container_highest};
        --interactive-active: ${colors.on_surface};

        --dracula-primary: ${colors.surface};
        --dracula-secondary: ${colors.surface_dim};
        --dracula-secondary-alpha: ${colors.surface_dim}ee;
        --dracula-tertiary: ${colors.surface_bright};
        --dracula-tertiary-alpha: ${colors.surface_bright}aa;
        --dracula-primary-light: ${colors.surface_bright};

        --dracula-accent: ${colors.primary};
        --dracula-accent-alpha: ${colors.primary}66;
        --dracula-accent-alpha-alt: ${colors.secondary}88;
        --dracula-accent-alpha-alt2: ${colors.tertiary}aa;
        --dracula-accent-dark: ${colors.primary_fixed_dim};
        --dracula-accent-light: ${colors.primary_fixed};
      }

      html.theme-light #app-mount::after {
        content: none;
      }
    '';
in {
  programs.vesktop = {
    enable = true;
    customCss = {
      enable = true;
      text = customCSS;
      file = "base16";
    };
  };
}
