{
  imports = [
    ./rofi
    ./audacity.nix
    ./audioctrl.nix
    ./blender.nix
    ./deluge.nix
    ./filezilla.nix
    ./gimp.nix
    ./krita.nix
    ./messagers.nix
    ./obsidian.nix
    ./office.nix
    ./postman.nix
    ./resolve.nix
    ./spotify.nix
    ./thunar.nix
    ./vesktop.nix
  ];
}
