{
  config,
  pkgs,
  lib,
  ...
}: let
  c = config.colorscheme.colors;
  h = config.colorscheme.harmonized;
  cfg = config.programs.vesktop;
  customCSS =
    # scss
    ''
      /**
      * @name Luke's Nocturnal Variant
      * @version 1.0.0
      * @description Stylized, Autogenerated, clean. Nocturnal theme with custom font and badges.
      * @author Roottwo
      */

      @import url("https://slowstab.github.io/dracula/BetterDiscord/source.css");
      @import url("https://mulverinex.github.io/legacy-settings-icons/dist-native.css");
      @import url("https://xcruxiex.github.io/themes/themes-cores/nocturnal.css");
      @import url("https://xcruxiex.github.io/themes/core/badges.css");
      @import url("https://xcruxiex.github.io/themes/core/custom-font.css");
      @import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css"); /* Radial Status */
      :root {
        --backgroundColor01: ${c.surface};
        --backgroundColor02: ${c.surface_dim};
        --mainColor: ${c.primary};
        --gradientColor01: ${c.primary};
        --gradientColor02: ${c.tertiary};

        /* Better Hljs */
        --backgroundCode: ${c.surface};
        --backgroundName: ${c.surface}40;

        /* Radial Status */
        --rs-small-spacing: 2px;
        --rs-large-spacing: 3px;
        --rs-width: 2px;
        --rs-avatar-shape: 70%;
        --rs-online-color: ${h.green};
        --rs-idle-color: ${h.yellow};
        --rs-dnd-color: ${h.red};
        --rs-offline-color: ${h.blue};
        --rs-streaming-color: ${h.magenta};
        --rs-invisible-color: ${h.cyan};
        --rs-phone-visible: block;
        --rs-phone-color: var(--rs-online-color);
        --customFont: 'gg sans', sans-serif;
      }

      .theme-dark, .theme-light, :root {
        --text-default: ${c.on_surface};
        --header-primary: ${c.on_surface};
        --header-secondary: ${c.on_surface_variant};
        --channeltextarea-background: ${c.surface_container};
        --interactive-normal: ${c.surface_container_highest};
        --interactive-active: ${c.on_surface};

        --dracula-primary: ${c.surface};
        --dracula-secondary: ${c.surface_dim};
        --dracula-secondary-alpha: ${c.surface_dim}ee;
        --dracula-tertiary: ${c.surface_bright};
        --dracula-tertiary-alpha: ${c.surface_bright}aa;
        --dracula-primary-light: ${c.surface_bright};

        --dracula-accent: ${c.primary};
        --dracula-accent-alpha: ${c.primary}66;
        --dracula-accent-alpha-alt: ${c.secondary}88;
        --dracula-accent-alpha-alt2: ${c.tertiary}aa;
        --dracula-accent-dark: ${c.primary_fixed_dim};
        --dracula-accent-light: ${c.primary_fixed};
      }


      html.theme-light #app-mount::after {
        content: none;
      }
    '';
in {
  options.programs.vesktop = {
    enable = lib.mkEnableOption "discord";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.stable.vesktop;
      description = "The code package to use.";
    };

    customCss = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable Custom CSS";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [cfg.package];
    xdg.configFile."vesktop/themes/base16.css".text = customCSS;
  };
}
